"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class battery(object):
    __slots__ = ["switch", "inches", "timestamp"]

    __typenames__ = ["int32_t", "double", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.switch = 0
        self.inches = 0.0
        self.timestamp = ""

    def encode(self):
        buf = BytesIO()
        buf.write(battery._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">id", self.switch, self.inches))
        __timestamp_encoded = self.timestamp.encode('utf-8')
        buf.write(struct.pack('>I', len(__timestamp_encoded)+1))
        buf.write(__timestamp_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != battery._get_packed_fingerprint():
            raise ValueError("Decode error")
        return battery._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = battery()
        self.switch, self.inches = struct.unpack(">id", buf.read(12))
        __timestamp_len = struct.unpack('>I', buf.read(4))[0]
        self.timestamp = buf.read(__timestamp_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if battery in parents: return 0
        tmphash = (0x6dd2ce1f338e0bb9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if battery._packed_fingerprint is None:
            battery._packed_fingerprint = struct.pack(">Q", battery._get_hash_recursive([]))
        return battery._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

